volumes:
  keycloakdb:
    driver: local

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
      KC_DEBUG: 'true'
      KC_DB: 'mariadb'
      KC_DB_URL_HOST: 'keycloakdb'
      KC_DB_URL_DATABASE: 'keycloak'
      KC_DB_USERNAME: 'keycloakuser'
      KC_DB_PASSWORD: 'keycloakpassword'
      DEBUG_PORT: '*:8787'
    command:
      - 'start-dev'
      - '--http-port'
      - '8080'
      - '--debug'
    ports:
      - "8080:8080"
    volumes:
      - "./target/keycloak-1.0-SNAPSHOT.jar:/opt/keycloak/providers/extensions.jar:z"
  keycloakdb:
    image: mariadb:11
    expose:
      - "3306"
    ports:
      - "33067:3306"
    environment:
      MARIADB_ROOT_PASSWORD: supersecret
      MARIADB_DATABASE: keycloak
      MARIADB_USER: keycloakuser
      MARIADB_PASSWORD: keycloakpassword
    volumes:
      - keycloakdb:/var/lib/mysql
